// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201202154026_MyFirstMigration_4")]
    partial class MyFirstMigration_4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.GetData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(150);

                    b.Property<int?>("ContractCount");

                    b.Property<int?>("ContractNumber");

                    b.Property<int?>("Count");

                    b.Property<string>("Date")
                        .HasMaxLength(150);

                    b.Property<double?>("Discount");

                    b.Property<int?>("InvoiceNumber");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<double?>("NetSales");

                    b.Property<int?>("NoContractCount");

                    b.Property<double?>("PerSale");

                    b.Property<double?>("ReceivedMoney");

                    b.Property<double?>("RefundAmount");

                    b.Property<int?>("ReturnedCount");

                    b.Property<double?>("SalesTax");

                    b.Property<string>("YearSeason")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("GetData");
                });

            modelBuilder.Entity("Models.GetName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("GetName");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
