//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GetData", typeof(GetData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد قرار داد.
        /// </summary>
        public static string ContractCount {
            get {
                return ResourceManager.GetString("ContractCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قرار داد.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالص فروش.
        /// </summary>
        public static string NetSales {
            get {
                return ResourceManager.GetString("NetSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بدون قرار داد.
        /// </summary>
        public static string NoContractCount {
            get {
                return ResourceManager.GetString("NoContractCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فی فروش.
        /// </summary>
        public static string PerSale {
            get {
                return ResourceManager.GetString("PerSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ دریافتی.
        /// </summary>
        public static string ReceivedMoney {
            get {
                return ResourceManager.GetString("ReceivedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ برگشتی.
        /// </summary>
        public static string RefundAmount {
            get {
                return ResourceManager.GetString("RefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد برگشتی.
        /// </summary>
        public static string ReturnedCount {
            get {
                return ResourceManager.GetString("ReturnedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروش باارزش افزوده.
        /// </summary>
        public static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال فصل.
        /// </summary>
        public static string YearSeason {
            get {
                return ResourceManager.GetString("YearSeason", resourceCulture);
            }
        }
    }
}
